#!/bin/sh
menu=('清炒藕片 1' '肉末豆腐 2' '青椒炒蛋 1' '手撕包菜 1' '酱爆茄子 1' '番茄炒蛋 1' '丝瓜炒蛋 2' '黄瓜炒蛋 1' '肉丝跑蛋 2' '肉沫茄子 1' '丝瓜炒肉 1' '茭白炒肉 1' '红萝卜炒肉 2' '香菇肉片 3' '香干肉丝 1' '毛豆肉丝(不要雪菜) 2' '西葫芦炒肉 1' '宫爆鸡丁 5' '豆腐皮炒肉 1')
total=0
for i in "${menu[@]}";do
	item=($i)
	#echo ${item[0]}fff
	let total=total+${item[1]}
done
let num=($RANDOM+10000000000)%$total
foo=0
for i in "${menu[@]}";do
        item=($i)
	if [ $(($num-$foo)) -lt ${item[1]} ];then
		echo ${item[0]}
		exit 0
	fi
        let foo=foo+${item[1]}
done
